### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/hrbraddins#1]
- [ ] handle edge cases for quoting
- [ ] perhaps handle `;` / `|` separators (mebbe w/a pref dialog)?
- [ ] possibly add a `dplyr::select()` version?

**Comment by hrbrmstr** [comment]
also current `rename` thing doesn't work (but I never use rename so not sure what shld be there)
